import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-restaurant-delivery-platform-commission-recovery",
  "engine": "recovery",
  "title": "Restaurant Delivery Platform Commission Recovery",
  "shortTitle": "Delivery Platform Recovery",
  "tagline": "Reconcile every delivery order, commission, promotion, refund, tax, and settlement",
  "industry": "Restaurant Digital Channel Finance",
  "uiPort": 4583,
  "apiPort": 5583,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Unsupported delivery-platform deductions converted into settlement corrections and location-level margin improvement",
  "valueNarrative": "Match platform agreements and orders to POS tickets, promotions, cancellations, refunds, taxes, virtual cards, sponsored listings, and settlements.",
  "calculation": {
    "actualKey": "chargedFees",
    "expectedKey": "supportedFees",
    "actualLabel": "Platform Fees & Deductions",
    "expectedLabel": "Contract-Supported Fees",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Order, POS, commission, promotion, refund, and settlement evidence indicate recoverable restaurant delivery deductions.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("platform-agreement-library","DPR01","Platform agreement library","Reconcile platform agreement library using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed platform agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Platform agreement library Reference","text","DPR01-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("restaurant-and-brand-registry","DPR02","Restaurant and brand registry","Reconcile restaurant and brand registry using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed restaurant and brand registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Restaurant and brand registry Reference","text","DPR02-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("order-ingestion","DPR03","Order ingestion","Reconcile order ingestion using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed order ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Order ingestion Reference","text","DPR03-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("pos-order-matching","DPR04","POS order matching","Reconcile pos order matching using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed pos order matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","POS order matching Reference","text","DPR04-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("commission-rate-validation","DPR05","Commission-rate validation","Reconcile commission-rate validation using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed commission-rate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Commission-rate validation Reference","text","DPR05-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("delivery-and-service-fee-audit","DPR06","Delivery and service-fee audit","Reconcile delivery and service-fee audit using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed delivery and service-fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Delivery and service-fee audit Reference","text","DPR06-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("promotion-funding-allocation","DPR07","Promotion funding allocation","Reconcile promotion funding allocation using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed promotion funding allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Promotion funding allocation Reference","text","DPR07-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("refund-responsibility-analysis","DPR08","Refund responsibility analysis","Reconcile refund responsibility analysis using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed refund responsibility analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Refund responsibility analysis Reference","text","DPR08-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("cancellation-validation","DPR09","Cancellation validation","Reconcile cancellation validation using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed cancellation validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Cancellation validation Reference","text","DPR09-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("menu-price-and-tax-reconciliation","DPR10","Menu price and tax reconciliation","Reconcile menu price and tax reconciliation using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed menu price and tax reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Menu price and tax reconciliation Reference","text","DPR10-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("sponsored-listing-fee-audit","DPR11","Sponsored-listing fee audit","Reconcile sponsored-listing fee audit using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed sponsored-listing fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Sponsored-listing fee audit Reference","text","DPR11-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("chargeback-reconciliation","DPR12","Chargeback reconciliation","Reconcile chargeback reconciliation using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed chargeback reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Chargeback reconciliation Reference","text","DPR12-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("settlement-statement-audit","DPR13","Settlement statement audit","Reconcile settlement statement audit using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed settlement statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Settlement statement audit Reference","text","DPR13-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("platform-dispute-workflow","DPR14","Platform dispute workflow","Reconcile platform dispute workflow using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed platform dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Platform dispute workflow Reference","text","DPR14-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("recovered-settlement-ledger","DPR15","Recovered settlement ledger","Reconcile recovered settlement ledger using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed recovered settlement ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Recovered settlement ledger Reference","text","DPR15-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]}),
feature("brand-platform-and-location-analytics","DPR16","Brand platform and location analytics","Reconcile brand platform and location analytics using platform agreements, restaurant and virtual-brand records, marketplace orders, POS tickets, commissions, promotions, refunds, cancellations, taxes, advertising fees, and settlements.","Produce a governed brand platform and location analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["platformLocation","Platform / Restaurant","text","QuickDish / Harbor Kitchen #18"],["caseReference","Brand platform and location analytics Reference","text","DPR16-2026-001"],["chargedFees","Platform Fees & Deductions","currency",386000],["supportedFees","Contract-Supported Fees","currency",329500]],{amountField:"chargedFees",subjects:["Fast-casual chain","Virtual brand portfolio","Full-service restaurant group","Ghost kitchen","Franchise location cohort"]})
]);
