import test from 'node:test';import assert from 'node:assert/strict';import config from '../app.config.mjs';import {calculate,normalizeAI,amount,authorizeTransition,localRequest} from './recovery-domain.mjs';
test('zero and decimal amounts are exact; missing evidence is rejected',()=>{assert.equal(amount(0),0);assert.equal(amount('19.99'),1999);for(const x of [null,'',false,'1.001','NaN',-1])assert.throws(()=>amount(x));});
test('each configured calculator requires its actual evidence',()=>{for(const feature of config.features){if(config.calculation||feature.fields.some(f=>f.key==='allowedAmount'))assert.throws(()=>calculate(config,feature,{}));}});
test('no refund is invented from a zero input',()=>{const rule=config.calculation||{actualKey:'billedAmount',expectedKey:'allowedAmount'};const feature=config.features.find(f=>f.fields.some(x=>x.key===rule.expectedKey));const result=calculate(config,feature,{[rule.actualKey]:0,[rule.expectedKey]:0});assert.equal(result.potentialRecoveryCents,0);assert.equal(result.confidence,null);assert.equal(result.risk,'Not assessed');});
test('signed variance preserves over-reimbursement and credit direction',()=>{const rule=config.calculation||{actualKey:'billedAmount',expectedKey:'allowedAmount',direction:'actual-minus-expected'};const feature=config.features.find(f=>f.fields.some(x=>x.key===rule.expectedKey));const result=calculate(config,feature,{[rule.actualKey]:'10.01',[rule.expectedKey]:'10.00'});assert.equal(result.signedVarianceCents,rule.direction==='expected-minus-actual'?-1:1);});
test('AI prose and incomplete JSON cannot become successful briefs',()=>{for(const raw of ['not JSON','{}','{"headline":"done"}'])assert.throws(()=>normalizeAI(raw,config.features[0],'fixture'));});
test('approval requires a different authorized person and valid state',()=>{const record={status:'Review',payload:{__createdBy:'1'}};assert.throws(()=>authorizeTransition({id:1,role:'admin'},record,'Approved'));assert.throws(()=>authorizeTransition({id:2,role:'operator'},record,'Approved'));assert.equal(authorizeTransition({id:2,role:'reviewer'},record,'Approved'),true);assert.throws(()=>authorizeTransition({id:2,role:'admin'},{...record,status:'Open'},'Closed'));});
test('credential fill stays local and rejects cross-origin callers',()=>{const req={socket:{remoteAddress:'127.0.0.1'},hostname:'127.0.0.1',headers:{origin:'http://localhost:4000'}};assert.equal(localRequest(req),true);assert.equal(localRequest({...req,headers:{origin:'https://evil.example'}}),false);assert.equal(localRequest({...req,socket:{remoteAddress:'10.0.0.1'}}),false);});
if(config.engine==='cam')test('CAM area share and fee arithmetic are real domain calculations',()=>{assert.equal(calculate(config,config.features.find(f=>f.id==='pro-rata'),{tenantAreaSqFt:100,buildingAreaSqFt:1000,proRataPercent:9}).calculatedSharePercent,10);const r=calculate(config,config.features.find(f=>f.id==='admin-fees'),{feeBase:100,feePercent:5,billedAmount:7});assert.equal(r.expectedCents,500);assert.equal(r.potentialRecoveryCents,200);});
