const base=`http://127.0.0.1:${process.env.API_PORT||5583}`;
const health=await fetch(`${base}/api/health`).then(r=>r.json());if(health.status!=='ok')throw new Error('Health failed');
const credentials=await fetch(`${base}/api/auth/demo-credentials`).then(r=>r.json());
const login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:credentials.email,password:credentials.password})});if(!login.ok)throw new Error(`Login failed ${login.status}`);const {token}=await login.json();const headers={authorization:`Bearer ${token}`};
const app=await fetch(`${base}/api/app`,{headers}).then(r=>r.json());
const dashboard=await fetch(`${base}/api/dashboard`,{headers}).then(r=>r.json());if(dashboard.totals.records<app.features.length*15)throw new Error('Dashboard record total is incomplete');
for(const feature of app.features){
  const response=await fetch(`${base}/api/features/${feature.id}/records`,{headers});if(!response.ok)throw new Error(`${feature.id} records failed`);const data=await response.json();if(data.items.length<15)throw new Error(`${feature.id} has only ${data.items.length} records`);
  const values=Object.fromEntries(feature.fields.map(field=>[field.key,field.sample]));
  const calculated=await fetch(`${base}/api/features/${feature.id}/calculate`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({values})});if(!calculated.ok)throw new Error(`${feature.id} calculation failed`);const calculation=await calculated.json();if(!calculation.result?.headline||!Array.isArray(calculation.result.sections))throw new Error(`${feature.id} calculation shape invalid`);
}
const first=app.features[0];const values=Object.fromEntries(first.fields.map(field=>[field.key,field.sample]));
const createdResponse=await fetch(`${base}/api/features/${first.id}/records`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({values,title:'Automated smoke validation case'})});if(!createdResponse.ok)throw new Error('Create flow failed');const created=(await createdResponse.json()).item;
const investigatingResponse=await fetch(`${base}/api/features/${first.id}/records/${created.id}/transition`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({status:'Investigating',expectedVersion:created.payload?.__version??0})});if(!investigatingResponse.ok)throw new Error(`Transition flow failed ${investigatingResponse.status}`);const investigating=(await investigatingResponse.json()).item;
const transitioned=await fetch(`${base}/api/features/${first.id}/records/${created.id}/transition`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({status:'Review',expectedVersion:investigating.payload?.__version??0})});if(!transitioned.ok)throw new Error(`Transition flow failed ${transitioned.status}`);
const analytics=await fetch(`${base}/api/analytics`,{headers}).then(r=>r.json());if(analytics.modules.length!==app.features.length)throw new Error('Analytics coverage incomplete');
const audit=await fetch(`${base}/api/audit-events`,{headers}).then(r=>r.json());if(!audit.items.some(item=>item.object_reference===created.reference))throw new Error('Audit event missing');
const ruleFor=feature=>app.calculation??(feature.fields.some(field=>field.key==='allowedAmount')?{actualKey:'billedAmount',expectedKey:'allowedAmount',direction:'actual-minus-expected'}:null);
const ingestFeature=app.features.find(feature=>ruleFor(feature));const rule=ruleFor(ingestFeature);const ingestValues=Object.fromEntries(ingestFeature.fields.map(field=>[field.key,field.sample]));
const caseResponse=await fetch(`${base}/api/features/${ingestFeature.id}/records`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({values:ingestValues,title:'Automated smoke statement case'})});if(!caseResponse.ok)throw new Error('Statement case create failed');const statementCase=(await caseResponse.json()).item;
const supported=Number(ingestValues[rule.expectedKey]);const statementAmount=rule.direction==='expected-minus-actual'?Number((supported-10).toFixed(2)):Number((supported+10).toFixed(2));
const statement=`reference,description,amount\n${statementCase.reference},Smoke statement line,${statementAmount}\n`;
const ingestResponse=await fetch(`${base}/api/features/${ingestFeature.id}/ingest`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({text:statement,format:'csv',sourceFile:'smoke-statement.csv'})});if(!ingestResponse.ok)throw new Error(`Statement ingestion failed ${ingestResponse.status}`);const ingested=await ingestResponse.json();
if(ingested.reconciliation?.summary?.confirmedRecovery!==10)throw new Error(`Statement reconciliation did not confirm the source-line recovery (${ingested.reconciliation?.summary?.confirmedRecovery})`);
const replay=await fetch(`${base}/api/features/${ingestFeature.id}/ingest`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({text:statement,format:'csv',sourceFile:'smoke-statement.csv'})}).then(r=>r.json());if(!replay.alreadyIngested)throw new Error('Statement ingestion is not idempotent on checksum');
const ingests=await fetch(`${base}/api/statement-ingests`,{headers}).then(r=>r.json());if(!ingests.items.some(item=>item.id===ingested.ingestId&&item.feature_id===ingestFeature.id&&Number(item.confirmed_recovery)===10))throw new Error('Statement ingest was not persisted with its reconciliation');
const detail=await fetch(`${base}/api/statement-ingests/${ingested.ingestId}`,{headers}).then(r=>r.json());if(!detail.lines?.some(line=>line.reference===statementCase.reference&&line.reconciliation_status==='recovery_supported'&&Number(line.delta)===10&&line.provenance?.checksum===ingested.checksum))throw new Error('Stored statement line provenance is incomplete');
if(process.env.LIVE_AI==='1'&&health.ai.configured){const analyzed=await fetch(`${base}/api/features/${first.id}/analyze`,{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({values,analysisType:'smoke-validation'})});if(!analyzed.ok)throw new Error(`OpenRouter analysis failed ${analyzed.status}`);const result=(await analyzed.json()).result;if(!result.headline||!Array.isArray(result.metrics)||!Array.isArray(result.sections)||!Array.isArray(result.actions))throw new Error('Professional AI result shape invalid');}
console.log(`Smoke passed: login, ${app.features.length} feature tables, calculations, create/transition, statement ingestion with source-line recovery, analytics, and audit history${process.env.LIVE_AI==='1'&&health.ai.configured?', plus live OpenRouter rendering':''}.`);
